[project]
name = "week05"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel",
    "autogen-agentchat",
    "autogen-ext[openai]",
    "crewai",
    "langchain",
    "langchain-community",
    "langchain-mcp-adapters",
    "langchain-google-genai",
    "langchain-openai",
    "fastapi",
    "fastapi-mcp",
    "langgraph",
    "nest-asyncio",
    "tavily-python",
    "uvicorn",
    "a2a-sdk",
    "python-dotenv",
    "google-generativeai",
]
