[project]
name = "week05-homework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
	"python-dotenv",
	"mcp",
	"langchain-mcp-adapters",
	"langchain-core>=0.3.0",
	"langgraph>=1.0.0",
	"langgraph-checkpoint-sqlite>=2.0.0",
	"langchain-openai",
	"langchain-google-genai",
	"langchain>=1.2.12",
	"langchain-community>=0.4.1",
	"dashscope>=1.25.13",
	"fastapi>=0.135.1",
	"fastapi-mcp>=0.4.0",
	"tavily-python>=0.5.0",
]
